CREATE DATABASE CHATBOT;

-- Tabla de usuarios
CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50), 
    PHONE VARCHAR(20) UNIQUE,
    EMAIL VARCHAR(100) UNIQUE, 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de programadores
CREATE TABLE PROGRAMMERS(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100) UNIQUE,
    SKILLS VARCHAR(255), 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de citas
CREATE TABLE SCHEDULES(
    ID SERIAL PRIMARY KEY,
    DATE DATE,
    HOUR VARCHAR(8),
    DESCRIPTION VARCHAR(255), 
    ID_USER INT REFERENCES USERS(ID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de proyectos
CREATE TABLE PROJECTS(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100), 
    DELIVER_DATE DATE,
    STATUS VARCHAR(50),  --Planificación, Diseño, Implementación, Pruebas, Despliegue, Mantenimiento
    ID_SCHEDULE integer,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- asignar programadores a proyectos
CREATE TABLE PROJECT_PROGRAMMERS(
    PROJECT_ID INT REFERENCES PROJECTS(ID),
    PROGRAMMER_ID INT REFERENCES PROGRAMMERS(ID),
    PRIMARY KEY (PROJECT_ID, PROGRAMMER_ID)
);

-- Tabla de comentarios
CREATE TABLE COMMENTS(
    ID SERIAL PRIMARY KEY,
    CONTENT TEXT, 
    ID_USER INT REFERENCES USERS(ID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de pagos  
CREATE TABLE PAYMENTS(
    ID SERIAL PRIMARY KEY,
    AMOUNT DECIMAL(10, 2),
    DUE_DATE DATE,
    STATUS VARCHAR(20), -- Pendiente, Pagado
    ID_USER INT REFERENCES USERS(ID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para mejorar el rendimiento en consultas
CREATE INDEX idx_users_phone ON USERS(PHONE);
CREATE INDEX idx_schedules_date ON SCHEDULES(DATE); 
CREATE INDEX idx_projects_deliver_date ON PROJECTS(DELIVER_DATE);
CREATE INDEX idx_comments_id_user ON COMMENTS(ID_USER);
CREATE INDEX idx_payments_due_date ON PAYMENTS(DUE_DATE);

INSERT INTO PROGRAMMERS (NAME, PHONE, EMAIL, SKILLS)
VALUES ('KEVIN', '0998680754','estebanguanoluisa2002@gmail.com','FULLSTACK MERN');

INSERT INTO PROGRAMMERS (NAME, PHONE, EMAIL, SKILLS)
VALUES ('STEVEN', '099999999','steven@gmail.com','REACT, HTML, CSS');
