CREATE DATABASE CHATBOT;

CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(20),
    PHONE VARCHAR(17),
    EMAIL VARCHAR(50) UNIQUE
);

CREATE TABLE SCHEDULES(
    ID SERIAL PRIMARY KEY,
    DATE DATE,
    HOUR VARCHAR(8),
    DESCRIPTION VARCHAR(50),
    ID_USER INT REFERENCES USERS(ID)
);

CREATE TABLE COMMENTS(
    ID SERIAL PRIMARY KEY,
    CONTENT VARCHAR(50),
    ID_USER INT REFERENCES USERS(ID)
);
