const informacionKeywords = [
  "1",
  "información",
  "informacion",
  "info",
  "más información",
  "mas informacion",
  "productos",
  "servicios",
  "quiero saber más",
  "quisiera saber más",
  "cuéntame más",
  "cuentame más",
  "dime más",
  "dime más sobre",
  "háblame de",
  "hablame de",
  "qué ofreces",
  "que ofreces",
  "quiero conocer",
  "quisiera conocer",
  "qué es",
  "que es",
  "qué hacen",
  "que hacen",
  "qué hacen ustedes",
  "que hacen ustedes",
  "explícame",
  "explicame",
  "podrías explicarme",
  "podrias explicarme",
  "cuál es tu servicio",
  "cual es tu servicio",
  "cuáles son tus servicios",
  "cuales son tus servicios",
  "qué venden",
  "que venden",
  "qué tienen",
  "que tienen",
  "qué tienen disponible",
  "que tienen disponible",
  "qué opciones hay",
  "que opciones hay",
  "qué opciones tienen",
  "que opciones tienen",
  "qué ofrecen",
  "que ofrecen",
  "descripción",
  "descripción del servicio",
  "descripción de productos",
  "descripción de servicios",
  "descríbeme",
  "describeme",
  "dame detalles",
  "necesito información",
  "necesito informacion",
  "quiero saber",
  "quiero detalles",
  "quisiera información",
  "quisiera informacion",
  "podrías contarme",
  "podrias contarme",
  "cuéntame",
  "contame",
  "háblame",
  "hablame",
  "necesito saber",
  "busco información",
  "busco informacion",
  "en qué consisten",
  "en que consisten",
  "me interesa",
  "estoy interesado",
  "estoy interesada",
  "me gustaría saber",
  "me gustaria saber",
  "quisiera saber",
];

const consultaKeywords = [
  "2",
  "consulta",
  "consultas",
  "pregunta",
  "preguntas",
  "duda",
  "dudas",
  "aclaración",
  "aclaraciones",
  "ayuda",
  "asistencia",
  "soporte",
  "cuestión",
  "cuestiones",
  "explicación",
  "explicaciones",
  "resolver",
  "solucionar",
];

const agendarKeywords = [
  "3",
  "agendar",
  "cita",
  "reunión",
  "reservar",
  "calendario",
  "programar",
  "cita previa",
  "entrevista",
  "horario",
  "disponibilidad",
];

const comentariosKeywords = [
  "4",
  "comentario",
  "comentarios",
  "sugerencia",
  "sugerencias",
  "opinión",
  "opiniones",
  "feedback",
  "retroalimentación",
  "recomendación",
  "recomendaciones",
  "crítica",
  "críticas",
  "evaluación",
  "observación",
  "observaciones",
];

export {
  informacionKeywords,
  consultaKeywords,
  agendarKeywords,
  comentariosKeywords,
};
